// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4KC5mOlDF2JaDG2E78qKS7G33B7EXgqk',
    appId: '1:714403635333:web:fbdbb0b07826b5dbd249ec',
    messagingSenderId: '714403635333',
    projectId: 'create-schema-1',
    authDomain: 'create-schema-1.firebaseapp.com',
    storageBucket: 'create-schema-1.firebasestorage.app',
    measurementId: 'G-ZJ8GGR6CYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOqTkJNbInhFVYQHTMUfBHEpDVIh89dwI',
    appId: '1:714403635333:android:a6ca208fe8149042d249ec',
    messagingSenderId: '714403635333',
    projectId: 'create-schema-1',
    storageBucket: 'create-schema-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ZIp9W1ThJweMZVod-Yi4og3MYJsRyxE',
    appId: '1:714403635333:ios:5908661686a0e47bd249ec',
    messagingSenderId: '714403635333',
    projectId: 'create-schema-1',
    storageBucket: 'create-schema-1.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ZIp9W1ThJweMZVod-Yi4og3MYJsRyxE',
    appId: '1:714403635333:ios:5908661686a0e47bd249ec',
    messagingSenderId: '714403635333',
    projectId: 'create-schema-1',
    storageBucket: 'create-schema-1.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4KC5mOlDF2JaDG2E78qKS7G33B7EXgqk',
    appId: '1:714403635333:web:19f5b17d9cba6a5ed249ec',
    messagingSenderId: '714403635333',
    projectId: 'create-schema-1',
    authDomain: 'create-schema-1.firebaseapp.com',
    storageBucket: 'create-schema-1.firebasestorage.app',
    measurementId: 'G-NRWV3X3RRV',
  );
}
